version: '3.3'

services:
  postgres:
    container_name: pgcontainer
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      #POSTGRES_DB: tenutanadore
    networks:
      - backend
    ports:
      - "5432:5432"
    volumes: 
          # - ./postgres-data:/var/lib/postgresql/data
          # copy the sql script to create tables
          # - ./database/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
          - /var/lib/postgresql/data
          - ./database/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "82:80"
    depends_on:
      - postgres
    networks:
      - backend

  tenutanadore:
    build:
      context: .                          #docker file path (. means root directory)
      dockerfile: Dockerfile
    image: tenutanadore/microservice_tenutanadore
    container_name: microservice_tenutanadore
    ports:
      - "8081:8081"
    depends_on:
      - postgres
      # - pgadmin
    networks:
      - backend
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/tenutanadore
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=admin
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

volumes:
  data : {}

networks:
  backend: